# fly.toml app configuration file generated for fadating on 2023-12-11T13:18:50+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fadating"
primary_region = "sin"

[build]
  image = "anuotat/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="degx5o794"
  CloudinarySettings__ApiKey="167333138949254"  

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
